hamsterdb Embedded Database: ham::txn Class Reference
ham::txn Class Reference
#include <hamsterdb.hpp>
Public Member Functions
txn (ham_txn_t *t=0)
void abort ()
void commit ()
ham_txn_t * get_handle ()
Protected Attributes
ham_txn_t * m_txn
db * m_db
Detailed Description
A Transaction class
This class wraps structures of type ham_txn_t.
Definition at line 237 of file hamsterdb.hpp.
Constructor & Destructor Documentation
ham::txn::txn (ham_txn_t * t = 0) [inline]
Constructor
Definition at line 240 of file hamsterdb.hpp.
Member Function Documentation
void ham::txn::abort () [inline]
Abort the Transaction
Definition at line 244 of file hamsterdb.hpp.
References ham_txn_abort(), and m_txn.
void ham::txn::commit () [inline]
Commit the Transaction
Definition at line 252 of file hamsterdb.hpp.
References ham_txn_commit(), and m_txn.
ham_txn_t* ham::txn::get_handle () [inline]
Returns a pointer to the internal ham_txn_t structure.
Definition at line 260 of file hamsterdb.hpp.
References m_txn.
Referenced by ham::db::erase(), ham::db::find(), and ham::db::insert().
Field Documentation
db* ham::txn::m_db [protected]
Definition at line 266 of file hamsterdb.hpp.
ham_txn_t* ham::txn::m_txn [protected]
Definition at line 265 of file hamsterdb.hpp.
Referenced by abort(), commit(), and get_handle().
The documentation for this class was generated from the following file:
include/ham/hamsterdb.hpp