hamsterdb Embedded Database: ham::record Class Reference
ham::record Class Reference
#include <hamsterdb.hpp>
Public Member Functions
record (void *data=0, ham_size_t size=0, ham_u32_t flags=0)
record (const record &other)
record & operator= (const record &other)
void * get_data () const
void set_data (void *data)
ham_size_t get_size () const
void set_size (ham_size_t size)
ham_u32_t get_flags () const
void set_flags (ham_u32_t flags)
ham_record_t * get_handle ()
Protected Attributes
ham_record_t m_rec
Detailed Description
A record class.
This class wraps structures of type ham_record_t.
Definition at line 172 of file hamsterdb.hpp.
Constructor & Destructor Documentation
ham::record::record (void * data = 0, ham_size_t size = 0, ham_u32_t flags = 0) [inline]
Constructor
Definition at line 175 of file hamsterdb.hpp.
References ham_record_t::data, ham_record_t::flags, m_rec, and ham_record_t::size.
ham::record::record (const record & other) [inline]
Copy constructor.
Definition at line 183 of file hamsterdb.hpp.
Member Function Documentation
void* ham::record::get_data () const [inline]
Returns the record data.
Definition at line 193 of file hamsterdb.hpp.
References ham_record_t::data, and m_rec.
ham_u32_t ham::record::get_flags () const [inline]
Returns the flags of the record.
Definition at line 213 of file hamsterdb.hpp.
References ham_record_t::flags, and m_rec.
ham_record_t* ham::record::get_handle () [inline]
Returns a pointer to the internal ham_record_t structure.
Definition at line 223 of file hamsterdb.hpp.
References m_rec.
Referenced by ham::db::find(), ham::cursor::find_ex(), ham::cursor::insert(), ham::db::insert(), ham::cursor::move(), and ham::cursor::overwrite().
ham_size_t ham::record::get_size () const [inline]
Returns the size of the record.
Definition at line 203 of file hamsterdb.hpp.
References m_rec, and ham_record_t::size.
record& ham::record::operator= (const record & other) [inline]
Assignment operator.
Definition at line 187 of file hamsterdb.hpp.
References m_rec.
void ham::record::set_data (void * data) [inline]
Sets the record data.
Definition at line 198 of file hamsterdb.hpp.
References ham_record_t::data, and m_rec.
void ham::record::set_flags (ham_u32_t flags) [inline]
Sets the flags of the record.
Definition at line 218 of file hamsterdb.hpp.
References ham_record_t::flags, and m_rec.
void ham::record::set_size (ham_size_t size) [inline]
Sets the size of the record.
Definition at line 208 of file hamsterdb.hpp.
References m_rec, and ham_record_t::size.
Field Documentation
ham_record_t ham::record::m_rec [protected]
Definition at line 228 of file hamsterdb.hpp.
Referenced by get_data(), get_flags(), get_handle(), get_size(), operator=(), record(), set_data(), set_flags(), and set_size().
The documentation for this class was generated from the following file:
include/ham/hamsterdb.hpp